### ISSUE TITLE
Makefile:5: ../../include/Make/Script.make: No such file or directory

### ISSUE THREAD

**Issue by baditaflorin** [MoniaMolinari/OSM-roads-comparison#3]
florinb@florinb-VirtualBox:/usr/lib/grass71/scripts$ cd v.osm.acc/
florinb@florinb-VirtualBox:/usr/lib/grass71/scripts/v.osm.acc$ sudo make
Makefile:5: ../../include/Make/Script.make: No such file or directory
make: **\* No rule to make target `../../include/Make/Script.make'.  Stop.
florinb@florinb-VirtualBox:/usr/lib/grass71/scripts/v.osm.acc$ ^C
florinb@florinb-VirtualBox:/usr/lib/grass71/scripts/v.osm.acc$

**Comment by baditaflorin** [comment]
ubuntu 14.04

**Comment by khatrpaw** [comment]
Install Grass-Dev by the following commands.
sudo apt-get update
sudo apt-get install grass-dev
it will work.
